# -*- coding: utf-8 -*-
# Generated by Django 1.11.23 on 2019-12-08 21:18
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.manager


class Migration(migrations.Migration):

    dependencies = [("drchrono", "0001_initial")]

    operations = [
        migrations.AlterModelManagers(
            name="appointment", managers=[("today", django.db.models.manager.Manager())]
        ),
        migrations.AddField(
            model_name="appointment",
            name="checkin_time",
            field=models.DateTimeField(null=True),
        ),
    ]
