# -*- coding: utf-8 -*-
# Generated by Django 1.11.23 on 2019-12-08 22:12
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [("drchrono", "0002_auto_20191208_2118")]

    operations = [
        migrations.RenameField(
            model_name="appointment", old_name="checkin_time", new_name="check_in_time"
        )
    ]
