# -*- coding: utf-8 -*-
# Generated by Django 1.11.23 on 2019-12-09 00:39
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.manager


class Migration(migrations.Migration):

    dependencies = [("drchrono", "0003_auto_20191208_2212")]

    operations = [
        migrations.AlterModelManagers(
            name="appointment",
            managers=[("complete", django.db.models.manager.Manager())],
        ),
        migrations.AddField(
            model_name="appointment",
            name="final_wait_time",
            field=models.IntegerField(null=True),
        ),
    ]
